[package]
name = "amtrak-gtfs-rt"
version = "0.1.10"
license = "AGPL-3.0"
description = "Converts Amtrak Track-A-Train to valid GTFS-rt vehicle and trip information"
edition = "2021"

[lints.rust]
unused_must_use = "deny"
non_ascii_idents = "deny"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amtk = "0.1.0"
amtrak-api = "0.1.0"
base64 = "0.21.5"
chrono = "0.4.31"
chrono-tz = "0.8.4"
geojson = "0.24.1"
gtfs = "0.1.0"
gtfs-rt = "0.4.0"
gtfs-structures = "0.38.0"
openssl = "0.10.61"
reqwest = {version = "0.11", features = ["gzip","brotli","rustls-tls","deflate","cookies","mime_guess"]}
rust-crypto = "0.2.36"
serde = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1.35", features = ["full"] }
