[package]
name = "amtrak-gtfs-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amtk = "0.1.0"
amtrak-api = "0.1.0"
base64 = "0.21.5"
chrono = "0.4.31"
gtfs-rt = "0.4.0"
openssl = "0.10.59"
reqwest = "0.11.22"
rust-crypto = "0.2.36"
serde = "1.0.192"
serde_json = "1.0.108"
tokio = { version = "1.34", features = ["full"] }
